services:
  backend:
    build:
      context: ./Backend_new
      dockerfile: Dockerfile
    container_name: fintrack_backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend_new:/app
    environment:
      - DEBUG=1
    command: sh -c "python fintrack_backend/manage.py migrate && python fintrack_backend/manage.py runserver 0.0.0.0:8000"
    networks:
      - fintrack_network

  frontend:
    build:
      context: ./Frontend
      dockerfile: dockerfile
    container_name: fintrack_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      # Essential for hot reloading in some environments (WSL, Docker Toolbox)
      - WATCHPACK_POLLING=true
      - VITE_API_URL=http://3.27.89.158:8000/api/v1
    stdin_open: true
    tty: true
    networks:
      - fintrack_network
    depends_on:
      - backend
      - db

  db:
    build:
      context: ./Database
      dockerfile: Dockerfile
    container_name: fintrack_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fintrack_network

networks:
  fintrack_network:
    driver: bridge

volumes:
  postgres_data:
